### PR TITLE
fix json syntax error

### PR DESCRIPTION
**Pull request by alexisintech**

### CODE REVIEW

**Comment by rachelnabors** [comment]
*waits for deploy preview*

I won't let THAT happen again!

**Comment by alexisintech** [comment]
> _waits for deploy preview_
> 
> I won't let THAT happen again!

I'm sure pulling the PR and viewing locally is 10x faster

**Comment by rachelnabors** [comment]
I'm deep on custom roles docs. Reorienting for me will take about as long.

**Review by BRKalow — APPROVED** [review]
lgtm ship it

**Pull request merged**
