### PR TITLE
Introduce Prettier formatting; remove `vale` and `eslint` linting

### PR DESCRIPTION
**Pull request by bradlc**
- Remove `eslint` and associated config
- Remove `@vvago/vale` and associated config
- Remove `.prettierignore` – MDX files and `manifest.json` are no longer ignored
- Remove `vale`, `lint:prose`, and `lint:mdx` npm scripts
- Add `lint:formatting` script to check formatting (`prettier . --check`)
- Add `concurrently` to run lint scripts in parallel. `lint:formatting` is excluded for now until files have been formatted once
- Add Prettier config (`.prettierrc`)
- Add Prettier plugin for MDX files (see https://github.com/clerk/clerk/pull/443 for details)
- Update `format` npm script to use Prettier

Similar to the `clerk/clerk` PR, the following script was run to verify that the formatting does not alter the interpretation of the MDX files:

<details>
<summary>verify.mjs</summary>

```js
import fs from 'node:fs/promises'
import { compile as _compile } from '@mdx-js/mdx'
import glob from 'fast-glob'
import * as prettier from 'prettier'

const files = await glob('docs/**/*.mdx')

function normalizeNewline(str) {
  return str.replace(/\\r\\n/g, '\\n')
}

function removeFrontmatter(source) {
  return source.replace(/^---(?:\r?\n|\r)(?:([\s\S]*?)(?:\r?\n|\r))?---(?:\r?\n|\r|$)/, '')
}

async function compile(source) {
  return normalizeNewline(String(await _compile(removeFrontmatter(source))))
}

for (let filename of files) {
  let source = await fs.readFile(filename, 'utf-8')
  let options = await prettier.resolveConfig(filename)
  let formatted = await prettier.format(source, {
    ...options,
    filepath: filename,
    // ignore differences caused by code block formatting
    mdxFormatCodeBlocks: false
  })

  if ((await compile(source)) !== (await compile(formatted))) {
    console.log('Compiled output does not match:', filename)
  }
}
```
</details>

> [!NOTE]
> A follow-up PR will be opened to _apply_ formatting to files in the repo. Initially **code block** formatting will be disabled to allow for manual review of each block

### CODE REVIEW

**Comment by S3Prototype** [comment]
Have we decided we're not going to use Vale anymore, or is this a temporary removal?

**Comment by bradlc** [comment]
> _Have we decided we're not going to use Vale anymore, or is this a temporary removal?_

Sorry, I should have elaborated in the description. I spoke to @alexisintech last week and she was happy to remove all existing linting, except for the link checker. My understanding was that none of the vale/eslint stuff was actively being used.

**Review by S3Prototype — APPROVED** [review]

**Comment by royanger** [comment]
Hey, just wondering if there is a blocker here? I would love to see this merged, even just for my own experience.

**Comment by alexisintech** [comment]
> Hey, just wondering if there is a blocker here? I would love to see this merged, even just for my own experience.

I reached out to brad but I think he's been on PTO ?

**Comment by bradlc** [comment]
Hey all, this is good to go if I can get a new approval 🙏

Here is the follow-up branch that _applies_ the initial formatting: https://github.com/clerk/clerk-docs/compare/bradlc/formatting...bradlc/apply-formatting

In addition to applying the formatting the following changes are made on that branch:

- Normalize all code block meta to the new format, i.e. `{{ filename: '.env.local' }}`
- Add `prettier: false` to all code block meta so that the code blocks are not formatted. As discussed previously with @alexisintech we should aim to review each code block individually and remove this where possible
- Unignore `lint:formatting` script so that formatting is checked for PRs (via `lint` script)

**Review by LekoArts — APPROVED** [review]

**Pull request merged**
