### PR TITLE
Introduce Clerk Koa SDK (community)

### PR DESCRIPTION
**Pull request by dimkl**
Related PR for adding the icon: https://github.com/clerk/clerk-marketing/pull/920

### CODE REVIEW

**Comment by alexisintech** [comment]
hey friend! you can upload the koa icon like how I did in this PR for the clerk icon:
https://github.com/clerk/clerk-marketing/pull/908

16x16 svg

**Comment by dimkl** [comment]
!preview

**Comment by alexisintech** [comment]
hmm.. I pulled both branches and am trying to check locally, but it doesn't seem to be appearing. I don't see anything wrong with the code, so I think it's the SVG.

https://github.com/clerk/clerk-docs/assets/98043211/512b83f8-f6ae-4129-82b6-a232ebec9012

So then I test the SVG, and yes, it comes up as nothing?

Screenshot 2024-04-04 at 11 17 14

**Comment by S3Prototype** [comment]
@dimkl Soft reminder about this PR

**Comment by bradlc** [comment]
Hey! It looks like your PR makes changes to the `docs/manifest.json` file. The manifest schema was recently updated so you will need to update your PR to account for this. You can see the updated documentation for the manifest here: https://github.com/clerk/clerk-docs/blob/main/CONTRIBUTING.md#navigation-manifest

If you need help with this, or would like me to make the necessary changes on your behalf please tag me in this PR or DM me on Slack 🤙

**Comment by dimkl** [comment]
Both PRs rebased and updated! 
@alexisintech , @S3Prototype , @bradlc PTAL

**Review by S3Prototype — APPROVED** [review]
Looks good 👍 I approved the other PR as well that adds the icon

**Pull request merged**
