### PR TITLE
feat: Add faq section to help address some common questions

### PR DESCRIPTION
**Pull request by royanger**
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1771/references/chrome-extension/overview#frequently-asked-questions-faq

### Explanation:

This adds a FAQ to reinforce questions that customers have and provide more details. This can be expanded in the future too to cover additional pain points.

### Checklist

- [x] I have clicked on "Files changed" and performed a thorough self-review
- [x] I have added the "deploy-preview" label and added the preview link(s) to this PR description
- [x] All existing checks pass

### CODE REVIEW

**Comment by victoriaxyz** [comment]
Hey @royanger! Here's the commit for my update: [666d829](https://github.com/clerk/clerk-docs/pull/1771/commits/666d829f58b973d1cf62544ebae279d26ba2ce90)

Feel free to call on Tuple if you have any questions. :)

**Comment by alexisintech** [comment]
looks like the commits got messed up, but victoria mentioned she will fix in the morning!

**Comment by victoriaxyz** [comment]
@royanger You can see the change here: https://github.com/clerk/clerk-docs/pull/1771/commits/bb41afcd8837f030d8eacb1b42bc7703329971f9

**Review by alexisintech — APPROVED** [review]
lgtm 😸💖

**Comment by royanger** [comment]
Thanks for the reviews.

**Pull request merged**
