### PR TITLE
Add locked to User class

### PR DESCRIPTION
**Pull request by iamjameswalters**
### Explanation:

Documents my changes in clerk-javascript [PR #3748](https://github.com/clerk/javascript/pull/3748)

### CODE REVIEW

**Review by jescalan — APPROVED** [review]
LGTM, but dependent on the implementation PR merging, so let's hold on merge until that happens

**Comment by alexisintech** [comment]
adding blocked label until [clerk/javascript#3748](https://github.com/clerk/javascript/pull/3748) is merged

**Comment by alexisintech** [comment]
@iamjameswalters @jescalan looks like the clerk/javascript PR was merged. is this PR good to merge?

**Comment by iamjameswalters** [comment]
That's right, it has been merged. It's a go from me!

**Comment by jescalan** [comment]
Thanks so much for the contribution @iamjameswalters! 🎉

**Pull request merged**
