### PR TITLE
Update Input Fields for Email Validation and Verification Process in `shadcn-ui` Example Forms

### PR DESCRIPTION
**Pull request by nabarvn**
This PR introduces several updates to enhance the handling of email input fields and the email verification process within the sign-up and sign-in forms. These changes aim to improve user experience and data validation.

**Modifications**
   1. Email Input Type:
      - Changed input type to `email` in the sign-up form to ensure proper email validation.

   2. Email Verification:
      - Updated verification strategy fields to accurately reflect the email verification process.
      - Adjusted field names for consistency in email verification steps.

**Benefits**
   - Enhanced user experience through more intuitive and accurate email input handling.
   - Improved data validation for email fields, reducing errors and ensuring proper email formats.
   - Consistency in the email verification process, making it clearer for developers.

**Screenshot Reference**

> [!NOTE]
> In the <Clerk.Field/> component of email verification code, there is no `email_code` option for `name` attribute.

elements-shadcn-ui-example

These improvements streamline the authentication process using Clerk Elements and ensure a better, more consistent experience for the developers who want to build custom UIs on top of Clerk's APIs.

### CODE REVIEW

**Comment by alexisintech** [comment]
Tagging in @alexcarpenter who worked on these examples. I like these updates, but want to tag him so he can have visibility on this. Awaiting your thoughts, Alex!

**Review by alexcarpenter — APPROVED** [review]
Looks good, thanks for the fix @nabarvn!

**Comment by nabarvn** [comment]
> Tagging in @alexcarpenter who worked on these examples. I like these updates, but want to tag him so he can have visibility on this. Awaiting your thoughts, Alex!

Appreciate you, @alexisintech.

**Comment by nabarvn** [comment]
Thanks for the quick approval @alexcarpenter!

**Pull request merged**
