### PR TITLE
Fix async code in basic-rbac.mdx

### PR DESCRIPTION
**Pull request by OwaisSiddiqui**
I was using to implement basic RBAC and ended at step 6 and the page was not redirecting when I was not logged in. I found out the checkRole function is async so I need to await it first. 

Note 1: I didn't update the checkRole for step 7 which also needs await from I can tell.
Note 2: Add an import { checkRole } from '@/utils/roles' for checkRole function

> [!IMPORTANT]
> 🔎 Previews:
>
> -

### This PR:

-

### CODE REVIEW

**Comment by alexisintech** [comment]
did you mean to leave this as a draft? and were you going to update the other things you mentioned?

**Comment by OwaisSiddiqui** [comment]
I did change it to draft since it's not complete yet I believe.

And no, I was hoping a member of the Clerk team would fix the code since I don't know if the rest if fine or not but I just opened this to notify you guys about it. Sorry, I am not fully sure about the rest of the code.

**Comment by royanger** [comment]
> Yes I did since it's I did not completely fix the async code in the rest of the docs as I mentioned in my note.
> 
> And no, I was hoping a member of the Clerk team would fix the code since I don't know if the rest if fine or not but I just opened this to notify you guys about it. Sorry, I am not fully sure about the rest of the code.

Hey @OwaisSiddiqui. Just out of curiousity, were you using Next 15 and/or @clerk/nextjs 6? I will be updating this guide for those later, but wanted to wee what your config was like when you ran into this issue.

**Comment by OwaisSiddiqui** [comment]
Hi @royanger, I am using Clerk v6 `@clerk/nextjs": "^6.0.2` and Next 14 `"next": "14.2.14"`.

**Comment by royanger** [comment]
Hey @OwaisSiddiqui, as you forked I couldn't edit your branch I created a new PR. Please take a look at https://github.com/clerk/clerk-docs/pull/1669 and let me know if you see any other issues. Thanks!

**Comment by OwaisSiddiqui** [comment]
Hi @royanger, LGTM!

**Comment by royanger** [comment]
> Hi @royanger, LGTM!

Thank you! I will close this PR in favour of the other one then. Thanks for the help.

**Pull request closed without merging**
